In [1]:
import pandas as pd
import datetime as dt

In [2]:
bikedata=pd.read_csv("C:/users/lalit/learnpanda/201902-citibike-tripdata.csv",low_memory=False)

In [3]:
bikedata.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,219,2019-02-01 00:00:06.2570,2019-02-01 00:03:46.1090,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,1
1,143,2019-02-01 00:00:28.0320,2019-02-01 00:02:51.7460,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,1
2,296,2019-02-01 00:01:13.9870,2019-02-01 00:06:10.7340,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,1
3,478,2019-02-01 00:01:14.1520,2019-02-01 00:09:12.7870,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,2
4,225,2019-02-01 00:01:49.3410,2019-02-01 00:05:34.4980,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,1

In [4]:
bikedata['starttime']= bikedata.starttime.apply(lambda d:dt.datetime.strptime(d, '%Y-%m-%d %H:%M:%S.%f'))

In [5]:
bikedata['startdate']=bikedata.starttime.apply(lambda d: d.date())
bikedata['start_time']=bikedata.starttime.apply(lambda d: d.time())

In [6]:
bikedata['stoptime']= bikedata.stoptime.apply(lambda d:dt.datetime.strptime(d, '%Y-%m-%d %H:%M:%S.%f'))

In [8]:
bikedata['stopdate']=bikedata.stoptime.apply(lambda d : d.date())
bikedata['stop_time']=bikedata.stoptime.apply(lambda d : d.time())

In [9]:
bikedata.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,start_time,stopdate,stop_time
0,219,2019-02-01 00:00:06.257,2019-02-01 00:03:46.109,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,1,2019-02-01,00:00:06.257000,2019-02-01,00:03:46.109000
1,143,2019-02-01 00:00:28.032,2019-02-01 00:02:51.746,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,1,2019-02-01,00:00:28.032000,2019-02-01,00:02:51.746000
2,296,2019-02-01 00:01:13.987,2019-02-01 00:06:10.734,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,1,2019-02-01,00:01:13.987000,2019-02-01,00:06:10.734000
3,478,2019-02-01 00:01:14.152,2019-02-01 00:09:12.787,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,2,2019-02-01,00:01:14.152000,2019-02-01,00:09:12.787000
4,225,2019-02-01 00:01:49.341,2019-02-01 00:05:34.498,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,1,2019-02-01,00:01:49.341000,2019-02-01,00:05:34.498000

In [10]:
def gender_dt(D):
    if (D == 1):
        return 'Male'
    elif (D== 2) :
        return 'Female'
    else :
        return 'Unknown'

In [11]:
bikedata['gender']=bikedata.gender.apply(lambda d : gender_dt(d))

KeyError: "['Gender'] not found in axis"

In [13]:
bikedata['age']=bikedata['birth year'].apply(lambda d: (dt.datetime.now().year- d) if(dt.datetime.now().year-d < 80) else 0)

In [14]:
bikedata.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,start_time,stopdate,stop_time,age
0,219,2019-02-01 00:00:06.257,2019-02-01 00:03:46.109,3494.0,E 115 St & Lexington Ave,40.797911,-73.942300,3501.0,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,Male,2019-02-01,00:00:06.257000,2019-02-01,00:03:46.109000,30
1,143,2019-02-01 00:00:28.032,2019-02-01 00:02:51.746,438.0,St Marks Pl & 1 Ave,40.727791,-73.985649,236.0,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,Male,2019-02-01,00:00:28.032000,2019-02-01,00:02:51.746000,29
2,296,2019-02-01 00:01:13.987,2019-02-01 00:06:10.734,3571.0,Bedford Ave & Bergen St,40.676368,-73.952918,3549.0,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,Male,2019-02-01,00:01:13.987000,2019-02-01,00:06:10.734000,32
3,478,2019-02-01 00:01:14.152,2019-02-01 00:09:12.787,167.0,E 39 St & 3 Ave,40.748901,-73.976049,477.0,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,Female,2019-02-01,00:01:14.152000,2019-02-01,00:09:12.787000,55
4,225,2019-02-01 00:01:49.341,2019-02-01 00:05:34.498,3458.0,W 55 St & 6 Ave,40.763094,-73.978350,3443.0,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,Male,2019-02-01,00:01:49.341000,2019-02-01,00:05:34.498000,40

In [15]:
bikedata['start station id'].fillna(0, inplace=True)
bikedata['end station id'].fillna(0, inplace=True)
bikedata['start station id']=bikedata['start station id'].astype(int)
bikedata['end station id']= bikedata['end station id'].astype(int)
bikedata['start station name'].fillna('UNKNOWN', inplace=True)
bikedata['end station name'].fillna('UNKNOWN', inplace=True)

In [16]:
bikedata.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,startdate,start_time,stopdate,stop_time,age
0,219,2019-02-01 00:00:06.257,2019-02-01 00:03:46.109,3494,E 115 St & Lexington Ave,40.797911,-73.942300,3501,E 118 St & Madison Ave,40.801487,-73.944251,33450,Subscriber,1989,Male,2019-02-01,00:00:06.257000,2019-02-01,00:03:46.109000,30
1,143,2019-02-01 00:00:28.032,2019-02-01 00:02:51.746,438,St Marks Pl & 1 Ave,40.727791,-73.985649,236,St Marks Pl & 2 Ave,40.728419,-73.987140,25626,Subscriber,1990,Male,2019-02-01,00:00:28.032000,2019-02-01,00:02:51.746000,29
2,296,2019-02-01 00:01:13.987,2019-02-01 00:06:10.734,3571,Bedford Ave & Bergen St,40.676368,-73.952918,3549,Grand Ave & Bergen St,40.678045,-73.962408,35568,Subscriber,1987,Male,2019-02-01,00:01:13.987000,2019-02-01,00:06:10.734000,32
3,478,2019-02-01 00:01:14.152,2019-02-01 00:09:12.787,167,E 39 St & 3 Ave,40.748901,-73.976049,477,W 41 St & 8 Ave,40.756405,-73.990026,25045,Subscriber,1964,Female,2019-02-01,00:01:14.152000,2019-02-01,00:09:12.787000,55
4,225,2019-02-01 00:01:49.341,2019-02-01 00:05:34.498,3458,W 55 St & 6 Ave,40.763094,-73.978350,3443,W 52 St & 6 Ave,40.761330,-73.979820,34006,Subscriber,1979,Male,2019-02-01,00:01:49.341000,2019-02-01,00:05:34.498000,40

In [57]:
bikedata.to_csv("C:\DataAnalytics\Bikedata0219.csv")

In [17]:
path_df1=bikedata[['start station id','start station name','start station latitude','start station longitude']].copy()

In [18]:
path_df1['path']=bikedata['start station id'].astype(str)+ '__'+ bikedata['end station id'].astype(str)

In [19]:
path_df1.head()

,start station id,start station name,start station latitude,start station longitude,path
0,3494,E 115 St & Lexington Ave,40.797911,-73.942300,3494__3501
1,438,St Marks Pl & 1 Ave,40.727791,-73.985649,438__236
2,3571,Bedford Ave & Bergen St,40.676368,-73.952918,3571__3549
3,167,E 39 St & 3 Ave,40.748901,-73.976049,167__477
4,3458,W 55 St & 6 Ave,40.763094,-73.978350,3458__3443

In [20]:
path_df1.columns = ['Stationid','Station_name', 'latitude',
      'longitude','path']
path_df1['type']='Start'

In [21]:
path_df1

,Stationid,Station_name,latitude,longitude,path,type
0,3494,E 115 St & Lexington Ave,40.797911,-73.942300,3494__3501,Start
1,438,St Marks Pl & 1 Ave,40.727791,-73.985649,438__236,Start
2,3571,Bedford Ave & Bergen St,40.676368,-73.952918,3571__3549,Start
3,167,E 39 St & 3 Ave,40.748901,-73.976049,167__477,Start
4,3458,W 55 St & 6 Ave,40.763094,-73.978350,3458__3443,Start
5,3078,Broadway & Roebling St,40.709248,-73.960631,3078__3016,Start
6,411,E 6 St & Avenue D,40.722281,-73.976687,411__317,Start
7,3628,Lenox Ave & W 117 St,40.802557,-73.949078,3628__3506,Start
8,293,Lafayette St & E 8 St,40.730207,-73.991026,293__383,Start
9,380,W 4 St & 7 Ave S,40.734011,-74.002939,380__3263,Start
10,236,St Marks Pl & 2 Ave,40.728419,-73.987140,236__3660,Start
11,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,3167__3168,Start
12,484,W 44 St & 5 Ave,40.755003,-73.980144,484__469,Start
13,327,Vesey Pl & River Terrace,40.715338,-74.016584,327__312,Start
14,3243,E 58 St & 1 Ave,40.758924,-73.962262,3243__3170,Start
15,362,Broadway & W 37 St,40.751726,-73.987535,362__478,Start
16,490,8 Ave & W 33 St,40.751551,-73.993934,490__508,Start
17,3107,Bedford Ave & Nassau Ave,40.723117,-73.952123,3107__3096,Start
18,3263,Cooper Square & Astor Pl,40.729515,-73.990753,3263__394,Start
19,336,Sullivan St & Washington Sq,40.730477,-73.999061,336__326,Start
20,515,W 43 St & 10 Ave,40.760094,-73.994618,515__325,Start
21,3170,W 84 St & Columbus Ave,40.785000,-73.972834,3170__3400,Start
22,3341,Central Park West & W 102 St,40.795346,-73.961860,3341__3547,Start
23,391,Clark St & Henry St,40.697601,-73.993446,391__3342,Start
24,3660,W 16 St & 8 Ave,40.741022,-74.001385,3660__487,Start
25,439,E 4 St & 2 Ave,40.726281,-73.989780,439__301,Start
26,507,E 25 St & 2 Ave,40.739126,-73.979738,507__491,Start
27,127,Barrow St & Hudson St,40.731724,-74.006744,127__238,Start
28,484,W 44 St & 5 Ave,40.755003,-73.980144,484__478,Start
29,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,270__3049,Start
...,...,...,...,...,...,...
943714,355,Bayard St & Baxter St,40.716021,-73.999744,355__296,Start
943715,3077,Stagg St & Union Ave,40.708771,-73.950953,3077__3058,Start
943716,355,Bayard St & Baxter St,40.716021,-73.999744,355__296,Start
943717,3258,W 27 St & 10 Ave,40.750182,-74.002184,3258__3258,Start
943718,3260,Mercer St & Bleecker St,40.727064,-73.996621,3260__368,Start
943719,355,Bayard St & Baxter St,40.716021,-73.999744,355__401,Start
943720,455,1 Ave & E 44 St,40.750020,-73.969053,455__454,Start
943721,486,Broadway & W 29 St,40.746201,-73.988557,486__3712,Start
943722,3407,Union St & Nevins St,40.679098,-73.987655,3407__3364,Start
943723,3718,E 11 St & Avenue B,40.727464,-73.979504,3718__312,Start
943724,3259,9 Ave & W 28 St,40.749370,-73.999234,3259__490,Start
943725,438,St Marks Pl & 1 Ave,40.727791,-73.985649,438__531,Start
943726,3093,N 6 St & Bedford Ave,40.717452,-73.958509,3093__460,Start
943727,3233,E 48 St & 5 Ave,40.757246,-73.978059,3233__3459,Start
943728,239,Willoughby St & Fleet St,40.691966,-73.981302,239__244,Start
943729,403,E 2 St & 2 Ave,40.725029,-73.990697,403__237,Start
943730,3714,Division Av & Hooper St,40.706842,-73.954435,3714__3068,Start
943731,2006,Central Park S & 6 Ave,40.765909,-73.976342,2006__3151,Start
943732,3531,Frederick Douglass Blvd & W 129 St,40.812551,-73.949229,3531__3293,Start
943733,3618,27 St & Hunter St,40.748500,-73.941275,3618__3142,Start
943734,438,St Marks Pl & 1 Ave,40.727791,-73.985649,438__410,Start
943735,3087,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,3087__389,Start
943736,423,W 54 St & 9 Ave,40.765849,-73.986905,423__3697,Start
943737,3572,34 Ave & 38 St,40.756913,-73.921631,3572__3616,Start
943738,3101,N 12 St & Bedford Ave,40.720798,-73.954847,3101__3087,Start
943739,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,2002__3656,Start
943740,229,Great Jones St,40.727434,-73.993790,229__519,Start
943741,494,W 26 St & 8 Ave,40.747348,-73.997236,494__487,Start
943742,3660,W 16 St & 8 Ave,40.741022,-74.001385,3660__3255,Start
943743,362,Broadway & W 37 St,40.751726,-73.987535,362__490,Start

In [22]:
path_df1['cnt']=path_df1.index

In [23]:
path_df1

,Stationid,Station_name,latitude,longitude,path,type,cnt
0,3494,E 115 St & Lexington Ave,40.797911,-73.942300,3494__3501,Start,0
1,438,St Marks Pl & 1 Ave,40.727791,-73.985649,438__236,Start,1
2,3571,Bedford Ave & Bergen St,40.676368,-73.952918,3571__3549,Start,2
3,167,E 39 St & 3 Ave,40.748901,-73.976049,167__477,Start,3
4,3458,W 55 St & 6 Ave,40.763094,-73.978350,3458__3443,Start,4
5,3078,Broadway & Roebling St,40.709248,-73.960631,3078__3016,Start,5
6,411,E 6 St & Avenue D,40.722281,-73.976687,411__317,Start,6
7,3628,Lenox Ave & W 117 St,40.802557,-73.949078,3628__3506,Start,7
8,293,Lafayette St & E 8 St,40.730207,-73.991026,293__383,Start,8
9,380,W 4 St & 7 Ave S,40.734011,-74.002939,380__3263,Start,9
10,236,St Marks Pl & 2 Ave,40.728419,-73.987140,236__3660,Start,10
11,3167,Amsterdam Ave & W 73 St,40.779668,-73.980930,3167__3168,Start,11
12,484,W 44 St & 5 Ave,40.755003,-73.980144,484__469,Start,12
13,327,Vesey Pl & River Terrace,40.715338,-74.016584,327__312,Start,13
14,3243,E 58 St & 1 Ave,40.758924,-73.962262,3243__3170,Start,14
15,362,Broadway & W 37 St,40.751726,-73.987535,362__478,Start,15
16,490,8 Ave & W 33 St,40.751551,-73.993934,490__508,Start,16
17,3107,Bedford Ave & Nassau Ave,40.723117,-73.952123,3107__3096,Start,17
18,3263,Cooper Square & Astor Pl,40.729515,-73.990753,3263__394,Start,18
19,336,Sullivan St & Washington Sq,40.730477,-73.999061,336__326,Start,19
20,515,W 43 St & 10 Ave,40.760094,-73.994618,515__325,Start,20
21,3170,W 84 St & Columbus Ave,40.785000,-73.972834,3170__3400,Start,21
22,3341,Central Park West & W 102 St,40.795346,-73.961860,3341__3547,Start,22
23,391,Clark St & Henry St,40.697601,-73.993446,391__3342,Start,23
24,3660,W 16 St & 8 Ave,40.741022,-74.001385,3660__487,Start,24
25,439,E 4 St & 2 Ave,40.726281,-73.989780,439__301,Start,25
26,507,E 25 St & 2 Ave,40.739126,-73.979738,507__491,Start,26
27,127,Barrow St & Hudson St,40.731724,-74.006744,127__238,Start,27
28,484,W 44 St & 5 Ave,40.755003,-73.980144,484__478,Start,28
29,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,270__3049,Start,29
...,...,...,...,...,...,...,...
943714,355,Bayard St & Baxter St,40.716021,-73.999744,355__296,Start,943714
943715,3077,Stagg St & Union Ave,40.708771,-73.950953,3077__3058,Start,943715
943716,355,Bayard St & Baxter St,40.716021,-73.999744,355__296,Start,943716
943717,3258,W 27 St & 10 Ave,40.750182,-74.002184,3258__3258,Start,943717
943718,3260,Mercer St & Bleecker St,40.727064,-73.996621,3260__368,Start,943718
943719,355,Bayard St & Baxter St,40.716021,-73.999744,355__401,Start,943719
943720,455,1 Ave & E 44 St,40.750020,-73.969053,455__454,Start,943720
943721,486,Broadway & W 29 St,40.746201,-73.988557,486__3712,Start,943721
943722,3407,Union St & Nevins St,40.679098,-73.987655,3407__3364,Start,943722
943723,3718,E 11 St & Avenue B,40.727464,-73.979504,3718__312,Start,943723
943724,3259,9 Ave & W 28 St,40.749370,-73.999234,3259__490,Start,943724
943725,438,St Marks Pl & 1 Ave,40.727791,-73.985649,438__531,Start,943725
943726,3093,N 6 St & Bedford Ave,40.717452,-73.958509,3093__460,Start,943726
943727,3233,E 48 St & 5 Ave,40.757246,-73.978059,3233__3459,Start,943727
943728,239,Willoughby St & Fleet St,40.691966,-73.981302,239__244,Start,943728
943729,403,E 2 St & 2 Ave,40.725029,-73.990697,403__237,Start,943729
943730,3714,Division Av & Hooper St,40.706842,-73.954435,3714__3068,Start,943730
943731,2006,Central Park S & 6 Ave,40.765909,-73.976342,2006__3151,Start,943731
943732,3531,Frederick Douglass Blvd & W 129 St,40.812551,-73.949229,3531__3293,Start,943732
943733,3618,27 St & Hunter St,40.748500,-73.941275,3618__3142,Start,943733
943734,438,St Marks Pl & 1 Ave,40.727791,-73.985649,438__410,Start,943734
943735,3087,Metropolitan Ave & Meeker Ave,40.714133,-73.952344,3087__389,Start,943735
943736,423,W 54 St & 9 Ave,40.765849,-73.986905,423__3697,Start,943736
943737,3572,34 Ave & 38 St,40.756913,-73.921631,3572__3616,Start,943737
943738,3101,N 12 St & Bedford Ave,40.720798,-73.954847,3101__3087,Start,943738
943739,2002,Wythe Ave & Metropolitan Ave,40.716887,-73.963198,2002__3656,Start,943739
943740,229,Great Jones St,40.727434,-73.993790,229__519,Start,943740
943741,494,W 26 St & 8 Ave,40.747348,-73.997236,494__487,Start,943741
943742,3660,W 16 St & 8 Ave,40.741022,-74.001385,3660__3255,Start,943742
943743,362,Broadway & W 37 St,40.751726,-73.987535,362__490,Start,943743

In [108]:
pathdf1= path_df1.rename(columns:{'start station id':'Station id','start station name': 'station name','start station latitude':'latitude','start station longitude':'longitude','path':'path'})

SyntaxError: invalid syntax (<ipython-input-108-ef1dbbf3cb2a>, line 1)

In [24]:
path_df2=bikedata[['end station id','end station name','end station latitude','end station longitude']].copy()

In [25]:
path_df2['path']=bikedata['start station id'].astype(str)+ '__'+ bikedata['end station id'].astype(str)

In [26]:
path_df2.columns = ['Stationid','Station_name', 'latitude',
      'longitude','path']
path_df2['type']='Destination'
path_df2['cnt']=path_df1.index

In [27]:
path_final=path_df1.append(path_df2,ignore_index=True)

In [28]:
path_final =path_final.groupby(['path','Stationid','Station_name','latitude','longitude','type']).agg('count')

In [29]:
path_final.reset_index(inplace=True)

In [30]:
path_final=path_final[path_final.path != '0__0']

In [31]:
path_final

,path,Stationid,Station_name,latitude,longitude,type,cnt
15,119__128,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
16,119__128,128,MacDougal St & Prince St,40.727103,-74.002971,Destination,1
17,119__144,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,5
18,119__144,144,Nassau St & Navy St,40.698399,-73.980689,Destination,5
19,119__2000,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,4
20,119__2000,2000,Front St & Washington St,40.702551,-73.989402,Destination,4
21,119__2023,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
22,119__2023,2023,E 55 St & Lexington Ave,40.759681,-73.970314,Destination,1
23,119__217,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,3
24,119__217,217,Old Fulton St,40.702772,-73.993836,Destination,3
25,119__239,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,21
26,119__239,239,Willoughby St & Fleet St,40.691966,-73.981302,Destination,21
27,119__242,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
28,119__242,242,Carlton Ave & Flushing Ave,40.697787,-73.973736,Destination,1
29,119__243,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,7
30,119__243,243,Fulton St & Rockwell Pl,40.688226,-73.979382,Destination,7
31,119__244,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
32,119__244,244,Willoughby Ave & Hall St,40.691960,-73.965369,Destination,1
33,119__245,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
34,119__245,245,Myrtle Ave & St Edwards St,40.693270,-73.977039,Destination,1
35,119__261,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,13
36,119__261,261,Johnson St & Gold St,40.694749,-73.983625,Destination,13
37,119__262,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
38,119__262,262,Washington Park,40.691782,-73.973730,Destination,1
39,119__270,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
40,119__270,270,Adelphi St & Myrtle Ave,40.693083,-73.971789,Destination,1
41,119__275,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
42,119__275,275,Washington Ave & Greene Ave,40.686501,-73.965633,Destination,1
43,119__278,119,Park Ave & St Edwards St,40.696089,-73.978034,Start,1
44,119__278,278,Concord St & Bridge St,40.697666,-73.984764,Destination,1
...,...,...,...,...,...,...,...
264011,83__421,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,2
264012,83__421,421,Clermont Ave & Park Ave,40.695734,-73.971297,Destination,2
264013,83__438,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264014,83__438,438,St Marks Pl & 1 Ave,40.727791,-73.985649,Destination,1
264015,83__460,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264016,83__460,460,S 4 St & Wythe Ave,40.712859,-73.965903,Destination,1
264017,83__467,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,4
264018,83__467,467,Dean St & 4 Ave,40.683125,-73.978951,Destination,4
264019,83__470,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264020,83__470,470,W 20 St & 8 Ave,40.743453,-74.000040,Destination,1
264021,83__473,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264022,83__473,473,Rivington St & Chrystie St,40.721101,-73.991925,Destination,1
264023,83__476,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264024,83__476,476,E 31 St & 3 Ave,40.743943,-73.979661,Destination,1
264025,83__481,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264026,83__481,481,S 3 St & Bedford Ave,40.712605,-73.962644,Destination,1
264027,83__502,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264028,83__502,502,Henry St & Grand St,40.714215,-73.981346,Destination,1
264029,83__516,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264030,83__516,516,E 47 St & 1 Ave,40.752069,-73.967844,Destination,1
264031,83__531,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264032,83__531,531,Forsyth St & Broome St,40.718939,-73.992663,Destination,1
264033,83__532,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264034,83__532,532,S 5 Pl & S 5 St,40.710451,-73.960876,Destination,1
264035,83__533,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264036,83__533,533,Broadway & W 38 St,40.752996,-73.987216,Destination,1
264037,83__539,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,1
264038,83__539,539,Metropolitan Ave & Bedford Ave,40.715348,-73.960241,Destination,1
264039,83__83,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Destination,7
264040,83__83,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,Start,7

In [32]:
path_final.to_csv("C:\DataAnalytics\Bikepath2019.csv")